Update 01-07
IT4Change/IT4C.dev pull request #15
Opened 2023-01-07 01:41 UTC by ulfgebhardt

## 🍰 Pullrequest

- removed todos as they are either done or available as issue

### Issues

- None

### Todo

- [X] None

2023-01-07 13:10 UTC, Tirokk requested changes
Hey cool! 🚀💫

Ich hab noch Vorschläge und Fragen …

2023-01-07 13:10 UTC, Tirokk commented on docs/index.md
> +**IT Team for Change**, in short **IT4C**, is a software developer team building software together. Our focus are out-of-the-box projects and disruptive civil tech to contribute to the inevitable cha
The wording `disruptive` can be discussed, like I said before.
But lets take it for now.

2023-01-07 13:10 UTC, Tirokk commented on docs/index.md
> +We believe in a working process that has the right amount of authority to make sensible decisions and coordinate us to reach our goals. The leadership may shift between team members based on expertis
```suggestion
We believe in a working process that has the right amount of authority to make sensible decisions and coordinate us to reach our goals. The leadership may shift between team members based on expertise and availability. Furthermore we believe that everyone who loves doing his job is more effective then when being forced to. We make sure every member has a great freedom to choose how to work.
```

2023-01-07 13:10 UTC, Tirokk commented on docs/index.md
> +Naturally we are a remote team spread throughout Europe (sometimes even further). The core of the team works together as of 2019 - see [history](./history.md). Our common denominator besides our love
> Our common denominator besides our love for social projects and the computer technology is the German language, even tho most of the professional work is done in English.

Why is this neccessary?

2023-01-07 13:10 UTC, Tirokk commented on docs/index.md
> +<!-- - busFaktor() e.V. -->
Why you have commented this?

2023-01-07 13:39 UTC, ulfgebhardt commented on docs/index.md
> +We believe in a working process that has the right amount of authority to make sensible decisions and coordinate us to reach our goals. The leadership may shift between team members based on expertis
this is wrong english.

I had `every member has a maximum of freedom` but the linter didnt like that

2023-01-07 13:40 UTC, ulfgebhardt commented on docs/index.md
> +Naturally we are a remote team spread throughout Europe (sometimes even further). The core of the team works together as of 2019 - see [history](./history.md). Our common denominator besides our love
I don't understand the question

2023-01-07 13:41 UTC, ulfgebhardt commented on docs/index.md
> +<!-- - busFaktor() e.V. -->
this is just an idea - it is unclear if we should support organisations on this page and which are orgas we want to feature

2023-01-07 13:45 UTC, ulfgebhardt commented on docs/index.md
> +We believe in a working process that has the right amount of authority to make sensible decisions and coordinate us to reach our goals. The leadership may shift between team members based on expertis
Please check this again, I made a new phrasing

2023-01-08 12:04 UTC, Tirokk approved these changes
👍🏼

2023-01-08 12:04 UTC, Tirokk commented on docs/index.md
> +We believe in a working process that has the right amount of authority to make sensible decisions and coordinate us to reach our goals. The leadership may shift between team members based on expertis
👍🏼

2023-01-08 12:05 UTC, Tirokk commented on docs/index.md
> +We believe in a working process that has the right amount of authority to make sensible decisions and coordinate us to reach our goals. The leadership may shift between team members based on expertis
Right

2023-01-08 12:29 UTC, Tirokk commented on docs/index.md
> +Naturally we are a remote team spread throughout Europe (sometimes even further). The core of the team works together as of 2019 - see [history](./history.md). Our common denominator besides our love
Translated this means:

> Unser gemeinsamer Nenner ist neben der Liebe zu sozialen Projekten und der Computertechnik die deutsche Sprache, auch wenn der Großteil der beruflichen Arbeit auf Englisch erfolgt.

If our common denominator is the German language that sounds exclusive to people of other languages. Or what you think?

2023-01-08 13:01 UTC, Tirokk approved these changes
💫

2023-01-08 13:02 UTC, merged