fix(content): wolle profile fixes
IT4Change/IT4C.dev pull request #39
Opened 2023-02-02 14:08 UTC by Tirokk

## 🍰 Pullrequest

Wolle profile fixes.

### Issues

- None

### Todo

- [X] None

2023-02-02 17:13 UTC, ulfgebhardt requested changes

2023-02-02 17:13 UTC, ulfgebhardt commented on docs/people/wolfgang-huss.md
> +  - Server adminitration
```suggestion
  - Server administration
```

2023-02-04 11:54 UTC, Tirokk commented on docs/people/wolfgang-huss.md
> +  - Server adminitration
Cool 🙏🏼

2023-02-04 13:47 UTC, ulfgebhardt approved these changes

2023-02-06 15:21 UTC, merged