feat(content): history
IT4Change/IT4C.dev pull request #42
Opened 2023-02-15 00:35 UTC by ulfgebhardt

## 🍰 Pullrequest

Start to work on the history of IT4C

### Issues

- None

### Todo

- [X] None

2023-02-20 11:48 UTC, Mogge requested changes

2023-02-20 11:48 UTC, Mogge commented on docs/history.md
> +Most of us met again 2019 at Human Connection. This time all as developers to <!-- textlint-disable write-good-->implement<!-- textlint-enable write-good --> the envisioned social network. [Wolle](pe
Links for Hannes and Moriz?

2023-02-20 11:48 UTC, Mogge commented on docs/history.md
> +With the end of the year 2022 the financial situation within the Gradido project became more dire, which lead to reduced hours for the team and [Wolle](people/wolfgang-huss.md) becoming a volunteer r
I am not sure if things like this should be published

2023-02-20 17:21 UTC, Tirokk requested changes
Cool cool 😍

See my suggestions and questions …

2023-02-20 17:21 UTC, Tirokk commented on docs/history.md
> +During 2022 the Yunite-Team approached the team to get a new social network going based on ocelot-social. The new network was release on 01.11.2022 under the name yunite.me.
Maybe a link to yunite.me?

```suggestion
During 2022 the Yunite-Team approached the team to get a new social network going based on *ocelot.social*. The new network was release on 01.11.2022 under the name [yunite.me](https://yunite.me).
```

2023-02-20 17:21 UTC, Tirokk commented on docs/history.md
> +In 2021 most of the team joined the Gradido project. As always our scout [Alex](people/alexander-friedland.md) was first, followed by [Ulf](people/ulf-gebhardt.md), who was residing in Norway at the
Maybe a link to Gradido?
Or to the project description here?

```suggestion
In 2021 most of the team joined the [Gradido](https://gdd.gradido.net) project. As always our scout [Alex](people/alexander-friedland.md) was first, followed by [Ulf](people/ulf-gebhardt.md), who was residing in Norway at the time. Soon after Moriz joined up and Hannes came on board in Summer 2021.
```

2023-02-20 17:21 UTC, Tirokk commented on docs/history.md
> +With the start of 2023 the IT4C brand name and [website](https://www.it4c.dev) was established to allow the whole team to present themselves and the team as a whole.
```suggestion
With the start of 2023 the IT4C brand name and [website](https://www.it4c.dev) was established to allow the team members to present themselves and the team as a whole.

```

2023-02-21 00:03 UTC, ulfgebhardt commented on docs/history.md
> +Most of us met again 2019 at Human Connection. This time all as developers to <!-- textlint-disable write-good-->implement<!-- textlint-enable write-good --> the envisioned social network. [Wolle](pe
Yes ofc. At the given time there was no Hannes or Moriz pages yet.

2023-10-03 08:25 UTC, mahula commented on docs/history.md
> +With the end of the year 2022 the financial situation within the Gradido project became more dire, which lead to reduced hours for the team and [Wolle](people/wolfgang-huss.md) becoming a volunteer r
Yes, they should not.

2023-10-03 08:35 UTC, mahula commented on docs/history.md
> +In 2021 most of the team joined the Gradido project. As always our scout [Alex](people/alexander-friedland.md) was first, followed by [Ulf](people/ulf-gebhardt.md), who was residing in Norway at the
We should use the gradido software repo URL here.

2023-10-03 08:45 UTC, mahula commented on docs/history.md
> +Most of us met again 2019 at Human Connection. This time all as developers to <!-- textlint-disable write-good-->implement<!-- textlint-enable write-good --> the envisioned social network. [Wolle](pe
Fixed in 9abb6ccf1df7a2620401777542f4838fb65eabf0

2023-10-03 08:47 UTC, mahula commented on docs/history.md
> +In 2021 most of the team joined the Gradido project. As always our scout [Alex](people/alexander-friedland.md) was first, followed by [Ulf](people/ulf-gebhardt.md), who was residing in Norway at the
Gradido software repo URL is now inserted - 80b3c7e8f8850b49a6ca10fbdf60da0afd78edce

2023-11-03 12:29 UTC, Tirokk commented on docs/history.md
> +In the last quater of 2020 Human Connection was ended as a project and the source code was republished under the name Ocelot.social. [Wolle](people/wolfgang-huss.md), [Alex](people/alexander-friedlan
done

2023-11-03 12:29 UTC, Tirokk commented on docs/history.md
> +During 2022 the Yunite-Team approached the team to get a new social network going based on ocelot-social. The new network was release on 01.11.2022 under the name yunite.me.
Done

2023-11-03 12:37 UTC, Tirokk approved these changes
I approve

2023-11-03 12:37 UTC, merged